title: "Neuromodulación y Neurotecnologías Emergentes: Base de Datos"
description: "Repositorio de bases de datos, registros y repositorios sobre neuromodulación y neurotecnologías emergentes: estimulación magnética transcraneal (TMS)"
author: "Juan Moisés de la Serna Tuya"
url: "https://juanmoisesd.github.io"
baseurl: "/neuromodulacion-y-neurotecnologias-emergentes-base-de-datos-tms-tdcs-dbs-e-inter"
