# Jekyll configuration for GitHub Pages
title: "neuromodulacion-y-neurotecnologias-emergentes-base-de-datos-tms-tdcs-dbs-e-inter"
description: "Repositorio de bases de datos, registros y repositorios sobre neuromodulación y neurotecnologías emergentes: estimulación magnética transcraneal (TMS), estimulación transcraneal por corriente directa (tDCS), estimulación cerebral profunda (DBS), inte"
url: "https://juanmoisesd.github.io"
baseurl: "/neuromodulacion-y-neurotecnologias-emergentes-base-de-datos-tms-tdcs-dbs-e-inter"

author:
  name: "Juan Moisés de la Serna Tuya"
  orcid: "0000-0002-8401-8018"
  linkedin: "https://www.linkedin.com/in/juanmoisesdelaserna/"
  scopus: "26632846700"
  institution: "Universidad Internacional de La Rioja (UNIR)"
  email: "juanmoises.delaserna@unir.net"

# SEO
tagline: "Open Research Dataset"
lang: "en"

# Social
twitter:
  username: juanmoisesd
  card: summary

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Build
theme: minima
include:
  - README.md
  - GLOSSARY.md
  - ABOUT_THE_AUTHOR.md
  - CITATION_GUIDE.md

# Exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
